services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    network_mode: host
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    env_file: ".env"
    deploy:
      resources:
        limits:
          memory: "16g"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file: ".env"
    deploy:
      resources:
        limits:
          memory: "1g"

  deepcool:
    build:
      context: .
      dockerfile: Dockerfile
      target: deepcool-run
    network_mode: host
    env_file: ".env"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "16m"

  emeter-logger:
    build:
      context: .
      dockerfile: Dockerfile
      target: emeter-run
    network_mode: host
    env_file: ".env"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "16m"

  envoy-logger:
    build:
      context: .
      dockerfile: Dockerfile
      target: envoy-run
    network_mode: host
    volumes:
      - ./envoy_data:/data
    env_file: ".env"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "16m"

volumes:
  influxdb_data:
      external: true
      name: emeterlog_influxdb_data
  grafana_data: {}
