services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    network_mode: host
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    env_file: ".env"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: "16g"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 2s
      retries: 10

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    env_file: ".env"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: "1g"

  deepcool:
    build:
      context: .
      dockerfile: Dockerfile
      target: deepcool-run
    network_mode: host
    env_file: ".env"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "16m"
    depends_on:
      influxdb:
        condition: service_healthy
      emeter-logger:
        condition: service_started
      envoy-logger:
        condition: service_started

  emeter-logger:
    build:
      context: .
      dockerfile: Dockerfile
      target: emeter-run
    network_mode: host
    env_file: ".env"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "16m"
    depends_on:
      influxdb:
        condition: service_healthy

  envoy-logger:
    build:
      context: .
      dockerfile: Dockerfile
      target: envoy-run
    network_mode: host
    volumes:
      - ./envoy_data:/data
    env_file: ".env"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "16m"
    depends_on:
      influxdb:
        condition: service_healthy

volumes:
  influxdb_data: {}
  grafana_data: {}
