services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    network_mode: host
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    env_file: ".env"
    deploy:
      resources:
        limits:
          memory: "1g"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file: ".env"
    deploy:
      resources:
        limits:
          memory: "256m"

  deepcool:
    build:
      dockerfile: cmd/deepcool/Dockerfile
    network_mode: host
    env_file: ".env"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "10m"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  emeter-logger:
    build:
      context: ../go-kasa
      dockerfile: cmd/emeterlog/Dockerfile
    network_mode: host
    env_file: ".env"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "16m"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  envoy-logger:
    build:
      context: ../go-envoy
      dockerfile: cmd/logger/Dockerfile
    network_mode: host
    volumes:
      - ./envoy_data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file: ".env"
    restart: unless-stopped
    command: ["./envoylog", "startup", "--token", "/data/envoy.jwt"]
    deploy:
      resources:
        limits:
          memory: "32m"

volumes:
  influxdb_data:
      external: true
      name: emeterlog_influxdb_data
  grafana_data: {}
