from(bucket: "energy")
  |> range(start: -15m)
  |> filter(fn: (r) => r["_measurement"] == "emeter")
  |> filter(fn: (r) => r["alias"] =~ /net-consumption-L[12]/)
  |> filter(fn: (r) => r["_field"] == "PowerMW")
  |> group(columns: ["_field"])
  |> mean()
  |> group()
  |> sum()
