{
 "title": "More Power!",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.measurementTagValues(bucket: \"energy\", tag: \"alias\", measurement: \"emeter\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Household Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "data = from(bucket: \"energy\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"emeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"VoltageMV\")\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000.0 }))\n  |> group() \n\ndata |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) |> map(fn: (r) => ({ _time: r._time, Average: r._value })) |> yield(name: \"avg\")\ndata |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)  |> map(fn: (r) => ({ _time: r._time, Min: r._value }))     |> yield(name: \"min\")\ndata |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)  |> map(fn: (r) => ({ _time: r._time, Max: r._value }))     |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Unaccounted for usage",
   "type": "timeseries",
   "description": "Somehow it should be possible to find the difference between these two.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.alias =~ /total-consumption-L[12]/)\n  // Average the Envoy phases over the window\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: true)\n  |> fill(value: 0.0)\n  // Sum L1 + L2\n  |> group(columns: [\"_time\"])\n  |> sum()\n  |> group()\n  |> map(fn: (r) => ({ _time: r._time, _value: float(v: r._value) / 1000.0 }))"
    },
    {
     "query": "from(bucket: \"energy\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"emeter\" and r._field == \"PowerMW\")\n  |> filter(fn: (r) => r.alias !~ /total-consumption|production|net-consumption/)\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: true)\n  |> fill(value: 0.0)\n  // STEP 2: Sum all the averaged plugs together\n  |> group(columns: [\"_time\"])\n  |> sum()\n  |> group()\n  |> map(fn: (r) => ({ _time: r._time, _value: float(v: r._value) / 1000.0 }))"
    },
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Watt of Power",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"emeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerMW\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000.0 }))\n  |> yield(name: \"watts\")"
    }
   ]
  },
  {
   "title": "Chaos Voltage View",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"emeter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"VoltageMV\")\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000.0 }))\n  |> map(fn: (r) => ({ r with _field: r.alias }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"per_device_avg\")"
    }
   ]
  }
 ]
}